import type { jsPDF } from 'jspdf';
import type { GraphImage, Report } from './types';
import { logoSvgMarkup } from '../../lib/logo';

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Convert a limited markdown subset (bold, inline code, bullet lists) to HTML. */
function mdToHtml(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  let inList = false;

  const inline = (s: string) =>
    escapeHtml(s)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');

  for (const line of lines) {
    const trimmed = line.trim();
    const bullet = trimmed.match(/^[-*]\s+(.*)$/);
    if (bullet) {
      if (!inList) {
        out.push('<ul>');
        inList = true;
      }
      out.push(`<li>${inline(bullet[1])}</li>`);
    } else {
      if (inList) {
        out.push('</ul>');
        inList = false;
      }
      if (trimmed) out.push(`<p>${inline(trimmed)}</p>`);
    }
  }
  if (inList) out.push('</ul>');
  return out.join('\n');
}

/** Build a standalone, self-styled HTML document for a report. */
export function reportToHtml(report: Report): string {
  const sections = report.sections
    .map((s) => {
      const evidence = s.citations.length
        ? `<p class="evidence">Evidence: ${s.citations
            .map((c) => `<code>${escapeHtml(c)}</code>`)
            .join(' ')}</p>`
        : '';
      const image = s.image
        ? `<div class="graph">${s.image.svg}</div>\n`
        : '';
      return `<section>\n<h2>${escapeHtml(s.title)}</h2>\n${image}${mdToHtml(s.body)}\n${evidence}\n</section>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(report.title)}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    max-width: 820px; margin: 40px auto; padding: 0 24px; color: #1a2330; line-height: 1.55; }
  header { border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { display: flex; align-items: center; gap: 9px; }
  .brand svg { display: block; }
  .brand-name { font-size: 14px; font-weight: 600; color: #3f6fd6; letter-spacing: .02em; }
  h1 { font-size: 24px; margin: 8px 0 4px; }
  .meta { color: #64748b; font-size: 13px; }
  h2 { font-size: 15px; text-transform: uppercase; letter-spacing: .04em; color: #334155; margin-top: 28px; }
  code { background: #f1f5f9; padding: 1px 5px; border-radius: 4px;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; }
  .evidence { font-size: 12px; color: #64748b; margin-top: 8px; }
  ul { padding-left: 20px; }
  .graph { margin: 12px 0 18px; }
  .graph svg { display: block; max-width: 100%; height: auto;
    border: 1px solid #e2e8f0; border-radius: 8px; }
  footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 12px; color: #94a3b8; }
</style>
</head>
<body>
<header>
  <div class="brand">${logoSvgMarkup(28)}<span class="brand-name">Drifters</span></div>
  <h1>${escapeHtml(report.title)}</h1>
  <div class="meta">${escapeHtml(report.id)} · ${escapeHtml(report.format.toUpperCase())} · ${escapeHtml(report.projectName)} · scan ${escapeHtml(report.scanId)} · run ${new Date(report.scanRunAt).toLocaleString()}</div>
</header>
${sections}
<footer>Generated by Drifters · ${new Date(report.createdAt).toLocaleString()}</footer>
</body>
</html>`;
}

/** Strip the limited markdown markers to plain text for PDF line rendering. */
function mdToPlain(text: string): string[] {
  return text.split('\n').map((line) => {
    const trimmed = line.trim();
    const bullet = trimmed.match(/^[-*]\s+(.*)$/);
    const content = (bullet ? bullet[1] : trimmed)
      .replace(/\*\*([^*]+)\*\*/g, '$1')
      .replace(/`([^`]+)`/g, '$1');
    return bullet ? `\u2022 ${content}` : content;
  });
}

/** Build a real PDF document for a report using jsPDF. */
export function reportToPdf(
  doc: jsPDF,
  report: Report,
  images?: Map<string, RasterImage>,
): jsPDF {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Brand mark: a badge with two offset layers (drift), then the wordmark.
  const badge = 15;
  const badgeY = y - 11;
  doc.setFillColor(37, 99, 235);
  doc.roundedRect(margin, badgeY, badge, badge, 3, 3, 'F');
  doc.setFillColor(147, 197, 253);
  doc.roundedRect(margin + 3, badgeY + 3.5, 6.5, 6.5, 1.5, 1.5, 'F');
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin + 5.5, badgeY + 6, 6.5, 6.5, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(37, 99, 235);
  doc.text('Drifters', margin + badge + 7, y);
  y += 20;

  // Title.
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(26, 35, 48);
  for (const line of doc.splitTextToSize(report.title, maxW)) {
    ensureSpace(24);
    doc.text(line, margin, y);
    y += 24;
  }

  // Meta line.
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  const meta = `${report.id} \u00b7 ${report.format.toUpperCase()} \u00b7 ${report.projectName} \u00b7 scan ${report.scanId} \u00b7 run ${new Date(report.scanRunAt).toLocaleString()}`;
  for (const line of doc.splitTextToSize(meta, maxW)) {
    ensureSpace(14);
    doc.text(line, margin, y);
    y += 14;
  }
  y += 4;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageW - margin, y);
  y += 22;

  for (const section of report.sections) {
    ensureSpace(28);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(51, 65, 85);
    doc.text(section.title.toUpperCase(), margin, y);
    y += 18;

    const img = images?.get(section.id);
    if (img) {
      let drawW = maxW;
      let drawH = (img.height / img.width) * drawW;
      const maxImgH = pageH - margin * 2;
      if (drawH > maxImgH) {
        drawH = maxImgH;
        drawW = (img.width / img.height) * drawH;
      }
      ensureSpace(drawH + 10);
      doc.addImage(img.data, 'PNG', margin, y, drawW, drawH);
      y += drawH + 14;
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(26, 35, 48);
    for (const para of mdToPlain(section.body)) {
      if (!para) {
        y += 6;
        continue;
      }
      for (const line of doc.splitTextToSize(para, maxW)) {
        ensureSpace(16);
        doc.text(line, margin, y);
        y += 15;
      }
    }

    if (section.citations.length) {
      ensureSpace(16);
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      const ev = `Evidence: ${section.citations.join(', ')}`;
      for (const line of doc.splitTextToSize(ev, maxW)) {
        ensureSpace(13);
        doc.text(line, margin, y);
        y += 13;
      }
    }
    y += 14;
  }

  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Drifters \u00b7 ${report.scanId} \u00b7 page ${p} of ${pageCount}`,
      margin,
      pageH - 24,
    );
  }

  return doc;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function safeName(report: Report): string {
  return report.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

/**
 * Download a report in its native format. HTML and JSON download as files
 * directly; PDF generates a true PDF via lazily-loaded jsPDF.
 */
export async function downloadReport(report: Report) {
  const name = safeName(report);

  if (report.format === 'json') {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    triggerDownload(blob, `${name}.json`);
    return;
  }

  if (report.format === 'pdf') {
    const { jsPDF } = await import('jspdf');
    const images = await rasterizeSectionImages(report);
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    reportToPdf(doc, report, images).save(`${name}.pdf`);
    return;
  }

  const html = reportToHtml(report);
  triggerDownload(new Blob([html], { type: 'text/html' }), `${name}.html`);
}

interface RasterImage {
  data: string;
  width: number;
  height: number;
}

/** Rasterize each section's graph SVG to a PNG data URL for PDF embedding. */
async function rasterizeSectionImages(report: Report): Promise<Map<string, RasterImage>> {
  const map = new Map<string, RasterImage>();
  for (const section of report.sections) {
    if (!section.image) continue;
    try {
      map.set(section.id, await svgToPng(section.image));
    } catch {
      // If rasterization fails, the section simply renders without its image.
    }
  }
  return map;
}

/** Convert a self-contained SVG to a PNG data URL via an offscreen canvas. */
function svgToPng(image: GraphImage): Promise<RasterImage> {
  return new Promise((resolve, reject) => {
    const blob = new Blob([image.svg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      try {
        const scale = 2; // render at 2x for crisp output
        const canvas = document.createElement('canvas');
        canvas.width = image.width * scale;
        canvas.height = image.height * scale;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          reject(new Error('Canvas 2D context unavailable'));
          return;
        }
        ctx.scale(scale, scale);
        ctx.drawImage(img, 0, 0);
        resolve({ data: canvas.toDataURL('image/png'), width: image.width, height: image.height });
      } catch (err) {
        reject(err instanceof Error ? err : new Error('Failed to rasterize SVG'));
      } finally {
        URL.revokeObjectURL(url);
      }
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to load SVG for rasterization'));
    };
    img.src = url;
  });
}
