import type { jsPDF } from "jspdf";
import type { Report } from "@/api/types";
import { FORMAT_META } from "@/features/reports/reportMeta";
import { brandLogoSvg } from "@/components/BrandLogo";

/** Convert a limited markdown subset (bold, inline code, bullet lists) to HTML. */
function mdToHtml(text: string): string {
  const lines = text.split("\n");
  const out: string[] = [];
  let inList = false;

  const inline = (s: string) =>
    escapeHtml(s)
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/`([^`]+)`/g, "<code>$1</code>");

  for (const line of lines) {
    const trimmed = line.trim();
    const bullet = trimmed.match(/^(?:[-*]|\d+\.)\s+(.*)$/);
    if (bullet) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${inline(bullet[1])}</li>`);
    } else {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      if (trimmed) out.push(`<p>${inline(trimmed)}</p>`);
    }
  }
  if (inList) out.push("</ul>");
  return out.join("\n");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Build a standalone, self-styled HTML document for a report. */
export function reportToHtml(report: Report): string {
  const sections = report.sections
    .map((s) => {
      const evidence = s.citations.length
        ? `<p class="evidence">Evidence: ${s.citations
            .map((c) => `<code>${escapeHtml(c)}</code>`)
            .join(" ")}</p>`
        : "";
      return `<section>
  <h2>${escapeHtml(s.title)}</h2>
  ${mdToHtml(s.body)}
  ${evidence}
</section>`;
    })
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(report.title)}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    max-width: 820px; margin: 40px auto; padding: 0 24px; color: #1a2330; line-height: 1.55; }
  header { border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
  .brand-name { font-size: 13px; font-weight: 600; color: #3f6fd6; letter-spacing: .02em; }
  h1 { font-size: 24px; margin: 0 0 4px; }
  .meta { color: #64748b; font-size: 13px; }
  h2 { font-size: 15px; text-transform: uppercase; letter-spacing: .04em;
    color: #334155; margin-top: 28px; }
  code { background: #f1f5f9; padding: 1px 5px; border-radius: 4px;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; }
  .evidence { font-size: 12px; color: #64748b; margin-top: 8px; }
  ul { padding-left: 20px; }
  footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px;
    font-size: 12px; color: #94a3b8; }
</style>
</head>
<body>
<header>
  <div class="brand">${brandLogoSvg(28)}<span class="brand-name">Architecture Drift Copilot</span></div>
  <h1>${escapeHtml(report.title)}</h1>
  <div class="meta">${escapeHtml(report.id)} · ${escapeHtml(report.format.toUpperCase())} · generated ${new Date(
    report.createdAt,
  ).toLocaleString()}</div>
</header>
${sections}
<footer>Generated by Architecture Drift Copilot · run ${escapeHtml(report.runId)}</footer>
</body>
</html>`;
}

/** Strip the limited markdown markers to plain text for PDF line rendering. */
function mdToPlain(text: string): string[] {
  return text.split("\n").map((line) => {
    const trimmed = line.trim();
    const bullet = trimmed.match(/^(?:[-*]|\d+\.)\s+(.*)$/);
    const content = (bullet ? bullet[1] : trimmed)
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/`([^`]+)`/g, "$1");
    return bullet ? `\u2022 ${content}` : content;
  });
}

/** Build a real PDF document for a report using jsPDF. */
export function reportToPdf(doc: jsPDF, report: Report): jsPDF {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Brand mark (vector): gradient-ish blue tile + white delta triangle.
  const logo = 22;
  doc.setFillColor(63, 111, 214);
  doc.roundedRect(margin, y, logo, logo, 5, 5, "F");
  doc.setFillColor(255, 255, 255);
  doc.triangle(
    margin + logo / 2,
    y + 4,
    margin + logo - 4,
    y + logo - 4,
    margin + 4,
    y + logo - 4,
    "F",
  );
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(63, 111, 214);
  doc.text("Architecture Drift Copilot", margin + logo + 10, y + logo / 2 + 4);
  y += logo + 16;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(26, 35, 48);
  for (const line of doc.splitTextToSize(report.title, maxW)) {
    ensureSpace(24);
    doc.text(line, margin, y);
    y += 24;
  }

  // Meta line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  const meta = `${report.id} \u00b7 ${report.format.toUpperCase()} \u00b7 generated ${new Date(
    report.createdAt,
  ).toLocaleString()}`;
  ensureSpace(16);
  doc.text(meta, margin, y);
  y += 10;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageW - margin, y);
  y += 22;

  for (const section of report.sections) {
    // Section heading
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(51, 65, 85);
    doc.text(section.title.toUpperCase(), margin, y);
    y += 18;

    // Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(26, 35, 48);
    for (const para of mdToPlain(section.body)) {
      if (!para) {
        y += 6;
        continue;
      }
      for (const line of doc.splitTextToSize(para, maxW)) {
        ensureSpace(16);
        doc.text(line, margin, y);
        y += 15;
      }
    }

    // Evidence
    if (section.citations.length) {
      ensureSpace(16);
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      const ev = `Evidence: ${section.citations.join(", ")}`;
      for (const line of doc.splitTextToSize(ev, maxW)) {
        ensureSpace(13);
        doc.text(line, margin, y);
        y += 13;
      }
    }
    y += 14;
  }

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Architecture Drift Copilot \u00b7 run ${report.runId} \u00b7 page ${p} of ${pageCount}`,
      margin,
      pageH - 24,
    );
  }

  return doc;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/**
 * Download a report in its native format. HTML and JSON download as files
 * directly; PDF generates a true PDF via lazily-loaded jsPDF.
 */
export async function downloadReport(report: Report) {
  const safeName = report.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  if (report.format === "json") {
    const blob = new Blob([JSON.stringify(report, null, 2)], {
      type: "application/json",
    });
    triggerDownload(blob, `${safeName}.json`);
    return;
  }

  if (report.format === "pdf") {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    reportToPdf(doc, report).save(`${safeName}.pdf`);
    return;
  }

  // html
  const html = reportToHtml(report);
  triggerDownload(new Blob([html], { type: "text/html" }), `${safeName}.html`);
}

export function formatLabel(report: Report): string {
  return FORMAT_META[report.format].label;
}
